version: '3.9'
services:
  tim:
    container_name: TIM
    build:
      context: .
    ports:
      - 8085:8085
    networks:
      - tim
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  tim:
    name: tim
    driver: bridge
    driver_opts:                         
       com.docker.network.driver.mtu: 1400
